name = "wildling"
description = "Pattern based string generator library and CLI"
version = "2.0.2"

authors = ["dotmonk"]
maintainers = ["dotmonk <dotmonk@users.noreply.github.com>"]
maintainers-logins = ["dotmonk"]

licenses = "MIT"
website = "https://github.com/dotmonk/wildling"
tags = ["pattern", "generator", "text"]

[[depends-on]]
gnat = ">=12"
