name = "wildling"
version = "2.0.1"
license = "MIT"
author = "dotmonk"
maintainer = "dotmonk@users.noreply.github.com"
copyright = "dotmonk"
homepage = "https://github.com/dotmonk/wildling"
description = "Pattern based string generator library and CLI"

[library]
source-dir = "src"
include-dir = "src"

[install]
library = true
